# Site settings
title: Albert Untung
email: aalbertuntung@gmail.com
description: "Albert Untung: a developer based in Toronto."
baseurl: "" # base
url: "http://albert.wtf/" # base

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE
  - README.md

github_username: aulb
linkedin_username: albert-untung
